# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-added-large-files
  -   id: check-toml
  -   id: mixed-line-ending

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.2
  hooks:
    - id: ruff

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
    - id: gitleaks
